apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace/arc-systems.yaml
  - namespace/arc-runners.yaml

helmCharts:
  - name: gha-runner-scale-set-controller
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.12.1
    includeCRDs: true
    namespace: arc-systems
    releaseName: arc

  - name: gha-runner-scale-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.12.1
    namespace: arc-runners
    releaseName: arc-runner-set-latest
    valuesMerge: replace
    valuesInline:
      githubConfigUrl: https://github.com/quipper/actions-runner
      githubConfigSecret: github-config
      controllerServiceAccount:
        namespace: arc-system
        name: arc-gha-rs-controller
      runnerScaleSetName: ARC_RUNNER_NAME-latest
      template:
        spec:
          containers:
            - name: runner
              image: ARC_RUNNER_IMAGE_LATEST_URI
              securityContext:
                privileged: true

  - name: gha-runner-scale-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.12.1
    namespace: arc-runners
    releaseName: arc-runner-set-ubuntu20
    valuesMerge: replace
    valuesInline:
      githubConfigUrl: https://github.com/quipper/actions-runner
      githubConfigSecret: github-config
      controllerServiceAccount:
        namespace: arc-system
        name: arc-gha-rs-controller
      runnerScaleSetName: ARC_RUNNER_NAME-ubuntu20
      template:
        spec:
          containers:
            - name: runner
              image: ARC_RUNNER_IMAGE_UBUNTU20_URI
              securityContext:
                privileged: true
