apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml

helmCharts:
  - name: gha-runner-scale-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.12.1
    namespace: arc-runners
    releaseName: runner-scale-set
    valuesMerge: replace
    valuesInline:
      githubConfigUrl: https://github.com/quipper/actions-runner
      githubConfigSecret: github-config
      controllerServiceAccount:
        namespace: arc-system
        name: arc-gha-rs-controller
      runnerScaleSetName: ARC_RUNNER_NAME
      template:
        spec:
          containers:
            - name: runner
              image: ARC_RUNNER_IMAGE_URI
              securityContext:
                privileged: true
