name: build-ubuntu20

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/reusable--build.yaml
    permissions:
      contents: read
      packages: write
    with:
      file: Dockerfile.ubuntu20
      flavor: suffix=-ubuntu20

  e2e-test:
    needs: build
    uses: ./.github/workflows/reusable--e2e-test.yaml
    secrets: inherit
    permissions:
      contents: read
      actions: write
    with:
      runner-image-uri: ${{ needs.build.outputs.image-uri }}
      runner-name: test-runner-${{ github.event.pull_request.number || github.ref_name }}-ubuntu20
      expected-image-os: ubuntu20
