name: e2e-test

on:
  workflow_call:
    inputs:
      runner-image-uri:
        description: image URI of runner
        type: string
        required: true

jobs:
  controller:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: e2e-test
    steps:
      - uses: actions/checkout@v3
      - uses: aquaproj/aqua-installer@v2.1.1
        with:
          aqua_version: v2.7.1
          working_directory: e2e-test
      - run: make cluster
      - run: make deploy
        env:
          RUNNER_IMAGE_URI: ${{ inputs.runner-image-uri }}
          APP_ID: ${{ secrets.E2E_TEST_APP_ID }}
          APP_INSTALLATION_ID: ${{ secrets.E2E_TEST_APP_INSTALLATION_ID }}
          APP_PRIVATE_KEY: ${{ secrets.E2E_TEST_APP_PRIVATE_KEY }}
      - run: make wait-for-job
      - run: make undeploy
        if: always()
      - run: make logs
        if: always()

  runner:
    runs-on: runner-scale-set-${{ github.run_id }}
    timeout-minutes: 10
    services:
      http:
        image: nginx:stable
        ports:
          - 8080:80
    steps:
      - uses: actions/checkout@v3

      # Test dockerd
      - run: docker version
      - run: docker run -v "$PWD:/workspace" --rm debian:stable ls -l /workspace/README.md
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          push: false
          context: e2e-test
          file: e2e-test/fixture.dockerfile

      # Test setup actions
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
      - run: ruby --version
      - run: gem --version
      - uses: actions/setup-python@v4
        with:
          python-version: 3
      - run: python --version

      # Test service container
      - run: curl -sf http://localhost:8080
