name: e2e-test

on:
  workflow_call:
    inputs:
      runner-image-uri:
        description: image URI of runner
        type: string
        required: true

jobs:
  controller:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: e2e-test
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: aquaproj/aqua-installer@294926f94b4233f202a2f03875c604f840cfed70 # v2.1.1
        with:
          aqua_version: v2.7.1
          working_directory: e2e-test
      - run: make cluster
      - run: make deploy
        env:
          RUNNER_IMAGE_URI: ${{ inputs.runner-image-uri }}
          APP_ID: ${{ secrets.E2E_TEST_APP_ID }}
          APP_INSTALLATION_ID: ${{ secrets.E2E_TEST_APP_INSTALLATION_ID }}
          APP_PRIVATE_KEY: ${{ secrets.E2E_TEST_APP_PRIVATE_KEY }}
      - run: make wait-for-job
      - run: make undeploy
        if: always()
      - run: make logs
        if: always()

  runner:
    runs-on: runner-scale-set-${{ github.run_id }}
    timeout-minutes: 10
    services:
      http:
        image: nginx:stable
        ports:
          - 8080:80
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      # Test dockerd
      - run: docker version
      - run: docker run -v "$PWD:/workspace" --rm debian:stable ls -l /workspace/README.md
      - uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2.5.0
      - uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4.0.0
        with:
          push: false
          context: e2e-test
          file: e2e-test/fixture.dockerfile

      # Test setup actions
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
      - run: ruby --version
      - run: gem --version
      - uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # v4.6.1
        with:
          python-version: 3
      - run: python --version

      # Test service container
      - run: curl -sf http://localhost:8080
