name: entrypoint / test

on:
  pull_request:
    paths:
      - .github/workflows/entrypoint--test.yaml
      - entrypoint.sh
      - entrypoint.d/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/entrypoint--test.yaml
      - entrypoint.sh
      - entrypoint.d/**

jobs:
  modify-apt-sources-aws-jammy-x86_64:
    runs-on: ubuntu-22.04 # jammy
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - run: sudo bash entrypoint.d/modify-apt-sources-aws-jammy-x86_64.sh us-east-1
      - run: sudo apt-get update

  modify-apt-sources-aws-jammy-aarch64:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
      # Test the script with qemu, because GitHub Actions does not support Arm for now
      - run: |
          docker run --rm -q --platform linux/arm64 \
            -v "$GITHUB_WORKSPACE:$GITHUB_WORKSPACE:ro" -w "$GITHUB_WORKSPACE" \
            ubuntu:jammy bash -eu -c "$script"
        env:
          script: |
            bash entrypoint.d/modify-apt-sources-aws-jammy-aarch64.sh us-east-1a
            apt-get update
