name: entrypoint / test

on:
  pull_request:
    paths:
      - .github/workflows/entrypoint--test.yaml
      - entrypoint.sh
      - entrypoint.d/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/entrypoint--test.yaml
      - entrypoint.sh
      - entrypoint.d/**

jobs:
  modify-apt-sources-jammy-x86_64:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: sudo bash entrypoint.d/modify-apt-sources-jammy-x86_64.sh us-east-1
      - run: sudo apt-get update

  modify-apt-sources-jammy-aarch64:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
      - run: docker run --rm -q --platform linux/arm64 -v "$GITHUB_WORKSPACE:$GITHUB_WORKSPACE" -w "$GITHUB_WORKSPACE" ubuntu:jammy bash -c "$script"
        env:
          script: |
            entrypoint.d/modify-apt-sources-jammy-aarch64.sh us-east-1a
            apt-get update
