name: entrypoint / test

on:
  pull_request:
    paths:
      - .github/workflows/entrypoint--test.yaml
      - entrypoint.sh
      - entrypoint.d/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/entrypoint--test.yaml
      - entrypoint.sh
      - entrypoint.d/**

jobs:
  modify-apt-sources-aws-jammy-x86_64:
    runs-on: ubuntu-22.04 # jammy
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: sudo bash entrypoint.d/modify-apt-sources-aws-jammy-x86_64.sh us-east-1
      - run: sudo apt-get update

  modify-apt-sources-aws-jammy-aarch64:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: docker/setup-qemu-action@5927c834f5b4fdf503fca6f4c7eccda82949e1ee # v3.1.0
      # Test the script with qemu, because GitHub Actions does not support Arm for now
      - run: |
          docker run --rm -q --platform linux/arm64 \
            -v "$GITHUB_WORKSPACE:$GITHUB_WORKSPACE:ro" -w "$GITHUB_WORKSPACE" \
            ubuntu:jammy bash -eu -c "$script"
        env:
          script: |
            bash entrypoint.d/modify-apt-sources-aws-jammy-aarch64.sh us-east-1a
            apt-get update
