name: rebuild-tags

on:
  pull_request:
    paths:
      - .github/workflows/build-tags.yaml
      - .github/workflows/reusable--build.yaml
  push:
    paths:
      - .github/workflows/build-tags.yaml
      - .github/workflows/reusable--build.yaml
  schedule:
    - cron: '21 0 * * *' # 7:00 Asia/Tokyo

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 2.317.0
    uses: ./.github/workflows/reusable--build.yaml
    permissions:
      contents: read
      packages: write
    with:
      context: ${{ github.server_url }}/${{ github.repository }}#refs/tags/${{ matrix.tag }}
      tags: ${{ matrix.tag }}
      push: ${{ github.event_name != 'pull_request' }}
      disable-build-cache: true

  build-ubuntu20:
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 2.317.0
    uses: ./.github/workflows/reusable--build.yaml
    permissions:
      contents: read
      packages: write
    with:
      context: ${{ github.server_url }}/${{ github.repository }}#refs/tags/${{ matrix.tag }}
      tags: ${{ matrix.tag }}
      file: Dockerfile.ubuntu20
      flavor: suffix=-ubuntu20
      push: ${{ github.event_name != 'pull_request' }}
      disable-build-cache: true
