name: build-and-test

on:
  workflow_call:
    inputs:
      context:
        type: string
        required: false
        description: context passed to docker/build-push-action
      build-args:
        type: string
        required: false
        description: build-args passed to docker/build-push-action
      tags:
        type: string
        required: false
        description: tags passed to docker/metadata-action
      flavor:
        type: string
        required: false
        description: flavor passed to docker/metadata-action
      runner-name:
        type: string
        required: true
        description: runner name
    outputs:
      image-uri:
        value: ${{ jobs.build.outputs.image-uri }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    outputs:
      image-uri: ghcr.io/${{ github.repository }}@${{ steps.build.outputs.digest }}
    steps:
      - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
          tags: ${{ inputs.tags }}
          flavor: ${{ inputs.flavor }}
      - uses: int128/docker-build-cache-config-action@4cb95f7b39060bdd7629745b83885dd955442583 # v1.16.0
        id: cache
        with:
          image: ghcr.io/${{ github.repository }}/cache
          flavor: ${{ inputs.flavor }}
      - uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
      - uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
      - uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        id: build
        with:
          context: ${{ inputs.context }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}
          build-args: ${{ inputs.build-args }}
          platforms: |
            linux/amd64
            linux/arm64

  e2e-test:
    needs: build
    uses: ./.github/workflows/reusable--e2e-test.yaml
    secrets: inherit
    with:
      runner-image-uri: ${{ needs.build.outputs.image-uri }}
      runner-name: ${{ inputs.runner-name }}
